# Generated by Django 4.1.7 on 2023-03-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='defs/default-avatar.jpg', upload_to='author_profile_photos/%Y/%M/'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='photo',
            field=models.ImageField(default='defs/default-avatar.jpg', upload_to='publisher_profile_photos/%Y/%M/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='book_covers/%Y/%M/%d'),
        ),
    ]
